POST http://localhost:8080/profile/adm/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU4NDA1NjEsImV4cCI6MTY1NjA1NjU2MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.hc-Zvy9Wi3V7b5HGp0IFqg_GYt_h3JPVG8B43hqLdq4

{
  "name": "Sardor",
  "surname": "Sardorov",
  "email": "sadik",
  "password": "2225",
  "role": "USER",
  "attachId": 1
}

###

PUT http://localhost:8080/profile/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU4NDA1NjEsImV4cCI6MTY1NjA1NjU2MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.hc-Zvy9Wi3V7b5HGp0IFqg_GYt_h3JPVG8B43hqLdq4

{
  "name": "Valijon",
  "surname": "Valijonov",
  "password": "123"
}


###

GET localhost:8080/profile/adm/list/USER
Authorization: Basic 1 123


###

DELETE http://localhost:8080/profile/delete/1
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2NTU4NDA1NjEsImV4cCI6MTY1NjA1NjU2MSwiaXNzIjoiTWF6Z2kgcHJvZHVjdGlvbiIsImlkIjoxLCJyb2xlIjoiQURNSU4ifQ.hc-Zvy9Wi3V7b5HGp0IFqg_GYt_h3JPVG8B43hqLdq4